### ISSUE TITLE
infer.py 在cpu机器上运行报错

### ISSUE THREAD

**Issue by rubby33** [BitVoyage/FastBERT#5]
infer.py 在gpu机器上运行正常(--gpu_ids='0,1')。
但是，infer.py 在cpu机器上运行报错(mac,--gpu_ids='-1')。
infer.py 在gpu机器上运行正常(ubuntu,--gpu_ids='-1)。
```
2020-06-12 15:16:02,461 - INFO - Load INFER Dataset Done, Total eval line: 3740
2020-06-12 15:16:02,462 - INFO - Inference Model...
Inference process:   0%|                                                | 0/3740 [00:00<?, ?batch/s]Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 324, in reduce_storage
    metadata = storage._share_filename_()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 324, in reduce_storage
    metadata = storage._share_filename_()
RuntimeError: error executing torch_shm_manager at "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/bin/torch_shm_manager" at ../torch/lib/libshm/core.cpp:99
RuntimeError: error executing torch_shm_manager at "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/bin/torch_shm_manager" at ../torch/lib/libshm/core.cpp:99
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 324, in reduce_storage
    metadata = storage._share_filename_()
RuntimeError: error executing torch_shm_manager at "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/bin/torch_shm_manager" at ../torch/lib/libshm/core.cpp:99
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 324, in reduce_storage
    metadata = storage._share_filename_()
RuntimeError: error executing torch_shm_manager at "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/bin/torch_shm_manager" at ../torch/lib/libshm/core.cpp:99

```

**Comment by BitVoyage** [comment]
像是安装环境的问题
